on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
name: 'release'
jobs:
  build:
    strategy:
      matrix:
        go-version:
          - '1.16.x'
        platform:
          - 'ubuntu-latest'
    runs-on: ${{ matrix.platform }}
    steps:
      - name: 'Install Go'
        uses: 'actions/setup-go@v2'
        with:
          go-version: ${{ matrix.go-version }}
      - name: 'Setup Environment'
        shell: 'bash'
        run: |
          git config --global core.autocrlf false
          echo 'GO111MODULE=on' >> $GITHUB_ENV
      - name: 'Install Releaser'
        shell: 'bash'
        run: |
          git clone https://github.com/goreleaser/goreleaser -b v0.159.0
          cd goreleaser
          go install
      - name: 'Install Versioner'
        shell: 'bash'
        run: |
          git clone https://github.com/calebcase/version -b v0.1.13
          cd version
          go install
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0
      - name: 'Tag'
        shell: 'bash'
        run: |
          git config --global user.email 'actions@github.com'
          git config --global user.name 'GitHub Actions'

          name="v$(version file)"
          git tag -a "$name" -m ''
      - name: 'Release'
        shell: 'bash'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          goreleaser
