on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
name: 'tests'
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - '1.13.x'
        platform:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
    runs-on: ${{ matrix.platform }}
    steps:
      - name: 'Install Go'
        uses: 'actions/setup-go@v1'
        with:
          go-version: ${{ matrix.go-version }}
      - name: 'Setup Environment'
        shell: 'bash'
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
          git config --global core.autocrlf false
      - name: 'Install Linter'
        shell: 'bash'
        run: |
          git clone https://github.com/golangci/golangci-lint -b v1.21.0
          cd golangci-lint/cmd/golangci-lint
          go install
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0
      - name: 'Lint'
        shell: 'bash'
        run: |
          golangci-lint run
      - name: 'Test'
        run: |
          go test ./...
